version: '3'

services:
  postgres:
    container_name: postgres for pytest
    image: postgres:latest
    port:
      - 5432:5432
    volumes:
      - docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES-DATABASE=in_system
      - DATABASE_HOST=localhost
