name: Container
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
      - name: Install Python
        run: |
          yum install -y https://centos7.iuscommunity.org/ius-release.rpm
          yum install python36u python36u-libs python36u-devel python36u-pip
          python --version        
