name: Container
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
      - name: Install Python
        run: |
          yum install -y https://repo.ius.io/ius-release-el7.rpm
          yum install python36u python36u-libs python36u-devel python36u-pip
        
