name: Docker Image CI

on:
  push:
    branches: [ master ]
jobs:
  test-docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout Repo
      uses: actions/checkout@v2
    - 
      name: Build Docker Container
      uses: docker://centos:7
    - 
      name: Install Python
      run: yum install -y python39u python39u-libs python39u-devel python39u-pip

