name: test_flake8
on:
  pull_request:
    branches:
      - main
jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout Repository
        uses: actions/checkout@v2
      - 
        name: Setup Python
        uses: actions/setup-python@v2
      - 
        name: Install Package
        run: |
          pip install flask
          pip install flask[async]
          pip install httpx
          pip install flake8
      -
        name: Check Flake8
        run: find . -name "*.py" -exec flake8 {} \;
