on: 
  push:
    branches:
      - 0.0.1

jobs:
  test_selenium:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout Repository
        uses: actions/checkout@v2
      - 
        name: Run docker
        uses: ./
