on: [push]

jobs:
  test_selenium:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout Repository
        uses: actions/checkout@v2
      - 
        name: Run docker
        uses: actions/docker@v1
